platform :ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '~> 2.5'
pod 'JSONModel', "~> 1.0"
pod 'Bolts', "~> 1.1"
pod 'SDWebImage', '~>3.6'
pod "PulsingHalo"
pod 'Masonry', '~> 0.6'
pod 'INTULocationManager', '~> 2.0'
pod 'BlocksKit', '~> 2.2'
